[build]
  publish = "dist"
  command = "npm run build"

# Allow the environment variable in build output
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_LISTEN_API_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200