[build]
  publish = "dist"
  command = "npm run build"

# Temporarily disable secret scanning to get the build working
[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200